name: invoiceninja_flutter
description: Mobile app for Invoice Ninja
version: 0.1.49
author: Hillel Coren
homepage: https://www.invoiceninja.com
documentation: http://docs.invoiceninja.com

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_redux: ^0.5.2
  redux_logging: ^0.3.0
  http: ^0.11.3+17
  in_app_purchase: ^0.2.1+2
  path_provider: ^0.5.0
  shared_preferences: ^0.4.2
  font_awesome_flutter: ^8.0.1
  built_value: ^6.1.2
  built_collection: ^4.0.0
  memoize: ^2.0.0
  url_launcher: ^3.0.3
  cached_network_image: ^0.8.0
  share: ^0.5.3
  intl: ^0.15.7
  flutter_slidable: ^0.4.6
  charts_flutter: ^0.6.0
  google_sign_in: ^4.0.4
  firebase_auth: ^0.14.0+5
  local_auth: ^0.5.2+4
  sentry: ^2.2.0
  image_picker: ^0.6.0+17
  flutter_pdfview: ^1.0.0+8
  #quick_actions: ^0.2.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: ^1.6.3
  #flutter_test:
  #  sdk: flutter
  build_runner: ^1.6.1
  built_value_generator: ^6.7.0
  faker: ^1.1.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
