name: invoiceninja_flutter
description: Client for Invoice Ninja
version: 5.0.156+156
homepage: https://invoiceninja.com
documentation: https://invoiceninja.github.io
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/mobile_icon.png"
  adaptive_icon_foreground: "assets/images/mobile_icon.png"
  adaptive_icon_background: "#0091EA"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #google_sign_in: ^6.0.1
  google_sign_in: 5.4.4 #https://pub.dev/packages/google_sign_in_web
  in_app_review: ^2.0.4
  in_app_purchase: ^3.1.1
  pinput: ^3.0.1
  #pinput: ^2.2.23
  #pinput:
  # git:
  #  url: https://github.com/Tkko/Flutter_Pinput
  #  ref: dev
  flutter_redux: ^0.10.0
  redux_logging: ^0.5.0
  http: ^0.13.3
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  material_design_icons_flutter: ^7.0.7296
  built_value: ^8.1.2
  built_collection: ^5.1.0
  memoize: ^3.0.0
  url_launcher: ^6.0.20
  share_plus: ^7.1.0
  intl: 0.17.0
  flutter_slidable: ^3.0.0
  charts_flutter: ^0.12.0
  #qr_flutter: ^4.0.0
  qr_flutter: # https://github.com/theyakka/qr.flutter/issues/174#issuecomment-1084235757
    git:
      url: https://github.com/theyakka/qr.flutter.git
  local_auth: ^2.1.5
  sentry_flutter: ^7.15.0
  image_picker: ^1.0.4
  flutter_colorpicker: ^1.0.3
  flutter_json_viewer: ^1.0.1
  webview_flutter: ^4.4.1
  timeago: ^3.1.0
  package_info: ^2.0.2
  rounded_loading_button: ^2.1.0
  version: ^3.0.2
  # flutter_launcher_icons: ^0.9.1
  overflow_view: ^0.3.1
  flutter_styled_toast: ^2.0.0
  permission_handler: ^11.0.1 # Disables Windows support to fix crash
  file_picker: ^5.2.5
  #boardview: ^0.2.2
  boardview:
    git:
      url: https://github.com/BenPoell/FlutterBoardView.git
  pointer_interceptor: ^0.9.0
  contacts_service: ^0.6.3
  diacritic: ^0.1.3
  states_rebuilder: ^6.2.0
  #super_editor: ^0.2.6
  #super_editor_markdown: ^0.1.5
  #markdown: ^5.0.0 # REMOVE THIS
  #super_editor_markdown:
  #  git:
  #    url: https://github.com/superlistapp/super_editor.git
  #    path: super_editor_markdown
  #    ref: stable
  html2md: ^1.2.6
  printing: ^5.11.0
  image_cropper: ^4.0.1
  msal_js: ^2.14.0
  sign_in_with_apple: ^5.0.0
  window_manager: ^0.3.0
  # bitsdojo_window: ^0.1.5
  intl_phone_field: ^3.1.0
  flutter_staggered_grid_view: ^0.7.0
  desktop_drop: ^0.4.1
  widget_kit_plugin: ^0.1.1
  pinch_zoom: ^1.0.0
  # quick_actions: ^0.2.1
  # idb_shim: ^1.11.1+1
  collection: ^1.15.0-nullsafety.4
  filesystem_picker: ^4.0.0
  device_info_plus: ^9.1.0
  ios_open_subscriptions_settings: ^0.0.4

dependency_overrides:
  intl: any
  navigation_builder: ^0.0.3
  states_rebuilder: ^6.3.0
  super_editor:
    git:
      url: https://github.com/superlistapp/super_editor
      path: super_editor
      ref: stable
  super_editor_markdown:
    git:
      url: https://github.com/superlistapp/super_editor
      path: super_editor_markdown
      ref: stable
  super_text_layout:
    git:
      url: https://github.com/superlistapp/super_editor
      path: super_text_layout
      ref: stable
  attributed_text:
    git:
      url: https://github.com/superlistapp/super_editor
      path: attributed_text
      ref: stable

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: ^1.6.3
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.0
  built_value_generator: ^8.1.1
  faker: ^2.0.0
  msix: ^3.5.1
  import_sorter: ^4.6.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/icon.png
    - assets/images/logo_light.png
    - assets/images/logo_dark.png
    - assets/images/google_logo.png
    - assets/images/payment_types/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/google_fonts/Roboto-Regular.ttf

msix_config:
  display_name: Invoice Ninja
  publisher_display_name: Invoice Ninja
  identity_name: InvoiceNinja.InvoiceNinja
  publisher: CN=2B7AA393-06A0-46F5-AF85-1917142440C3
  architecture: x64
  capabilities: 'internetClient'
  store: true
  logo_path: assets/images/icon.png