name: invoiceninja_flutter
description: Client for Invoice Ninja
version: 2.0.4+4
author: Hillel Coren
homepage: https://invoiceninja.com
documentation: http://docs.invoiceninja.com

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_redux: ^0.6.0
  redux_logging: ^0.4.0
  http: ^0.12.0+4
  in_app_purchase: ^0.3.1+1
  path_provider: ^1.6.1
  shared_preferences: ^0.5.6+2
  font_awesome_flutter: ^8.7.0
  built_value: ^7.0.9
  built_collection: ^4.3.2
  memoize: ^2.0.0
  cached_network_image: ^2.0.0
  url_launcher: ^5.4.2
  share: ^0.6.3+6
  #intl: ^0.16.1
  intl: any
  flutter_slidable: ^0.5.4
  charts_flutter: ^0.8.1
  google_sign_in: ^4.1.4
  firebase_auth: ^0.15.4
  local_auth: ^0.6.1+3
  sentry: ^3.0.1
  image_picker: ^0.6.3+4
  flutter_colorpicker: ^0.3.2
  flutter_json_widget: ^1.0.2
  webview_flutter: ^0.3.19+8
  timeago: ^2.0.26
  native_pdf_view: ^2.1.1
  flutter_typeahead: ^1.8.0
  flutter_share: ^1.0.2+1
  package_info: ^0.4.0+16
  device_info: ^0.4.2+1
  #quick_actions: ^0.2.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: ^1.6.3
  #flutter_test:
  #  sdk: flutter
  build_runner: ^1.7.4
  built_value_generator: ^7.0.9
  faker: ^1.1.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages


  fonts:
    - family: Roboto
      fonts:
        - asset: web/assets/fonts/Roboto-Regular.ttf

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
